include:
  - path: ./rabbitmq/docker-compose-rabbitmq.yaml
  - path: ../usersapi/docker-compose.yaml
  - path: ../catalogapi/docker-compose.yaml
  - path: ../paymentsapi/docker-compose.yaml
  - path: ../notificationsapi/docker-compose.yaml
  

networks:
  microsservicos-net:
    name: app-network
    driver: bridge